### ISSUE TITLE
Update to cats-effect 3

### ISSUE THREAD

**Issue by Z1kkurat** [evolution-gaming/pubsub#151]
This issue is just to remind that we still need to upgrade this library to cats-effect 3.  
As always, it's recommended to create a CE2-compatible branch before (`series/6.x.x`) to be able to back-port stuff

**Comment by olegkovalenko** [comment]
Working on it...

**Comment by olegkovalenko** [comment]
@Z1kkurat could you please review #163

**Comment by olegkovalenko** [comment]
pushed series/6.x.x branch to be able to back-port stuff
